name : Compilaci贸n del documento.tex de la carpeta Informes
on: 
  push:
  branches:
  - main # Detecta cambios en el repositorio principal para ejecutar el codigo

jobs:
  release_cv:
  name: "Ejecuci贸n Informe LaTex"
  runs-on: ubuntu-latest

  steps:
  name: "checkout master"
  uses: actions/checkout@v1

  name: "Compilaci贸n del Informe"
  uses: xu-cheng/latex-action@master
  with:
    root_file: Iformes/Indorme.tex

  name: "Revisi贸n del PDF"
  run:
    file Indorme.pdf | grep -q 'PDF'

  name: "Carga del PDF a un URL fija"
  uses: "marvinpinto/action-automatic-releases@latest"
  with:
    repo_token: "{{ secrets.PERSONAL_ACCESS_TOKEN}}"
    automati_release_tag: "latest"
    prerelease: true
    title: "Carga"
    files: 
      Indorme.pdf

  
  
  
